### ISSUE TITLE
No .\config/fsh/wook.ini  file.

### ISSUE THREAD

**Issue by hcnoh** [wookayin/dotfiles#13]
I have a error message while installing install.py:

Traceback (most recent call last):
  File "install.py", line 271, in <module>
    os.symlink(source, target)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hcnoh/.dotfiles/config/fsh/wook.ini' -> '/home/hcnoh/.config/fsh/wook.ini'

**Comment by wookayin** [comment]
Does the directory `~/.config/fsh` exist in your system? What about `.dotfiles/config/fsh/wook.ini`, etc.?

**Comment by hcnoh** [comment]
It was just a simple access authority problem to the directory ~/.config. Thanks for your reply.

**Comment by wookayin** [comment]
I see. I think this can be closed. Thanks for using and reporting!
