### ISSUE TITLE
Does rg require quote?

### ISSUE THREAD

**Issue by sungminoh** [wookayin/dotfiles#19]
https://github.com/wookayin/dotfiles/blob/b5a071c54cabe043ee5d39bd4151fe8992d9f6b5/vim/vimrc#L1017

It looks like rg literally consider quote as a character to search

Shouldn't it be just `nnoremap <leader>rg   :Rg ` (with trailing space)

**Comment by wookayin** [comment]
I think the behavior has changed. Previously `fzf.vim` parsed quote characters as shell expressions (e.g., to allow a query string with whitespaces) and it worked well. Now it does not. I will fix this. Thanks!
