### ISSUE TITLE
fzf floating window background color

### ISSUE THREAD

**Issue by sungminoh** [wookayin/dotfiles#20]
https://github.com/wookayin/dotfiles/blob/b5a071c54cabe043ee5d39bd4151fe8992d9f6b5/vim/vimrc#L941

https://github.com/wookayin/dotfiles/blob/b5a071c54cabe043ee5d39bd4151fe8992d9f6b5/vim/vimrc#L964

highlight doesn't work for one of my machines.

I fixed this by adding `  --color=bg:#1a2a31` at the end of the line 941.

Do you think it causes some other changes?

**Comment by wookayin** [comment]
Seems vim is not supporting 24-bit color. What does the `termguicolors` variable read?

```
set termguicolors?
```

In addition, how does your environments look like -- vim version, terminal emulator, etc.?

**Comment by sungminoh** [comment]
`echo &termguicolors` returns 1

iterms 3.3.7

nvim 0.4.3

**Comment by wookayin** [comment]
Closing as the issue being stale. Please re-open if you can reproduce the problem.
