### ISSUE TITLE
How can I turn off removing trailing whitespace?

### ISSUE THREAD

**Issue by liveseongho** [wookayin/dotfiles#26]
Hi, 

When I save markdown file (.md file which is set filetype "pandoc") on vim, it automatically removes trailing whitespace.
But, I used trailing whitespace on markdown for list indentation. Now, I should add a backslash to where I put two trailing spaces.

How can I turn off removing trailing whitespace?
I tried to comment out [line 878 and 879 in .vimrc](https://github.com/wookayin/dotfiles/blob/765d9275df57315af07869c768e0a64f3a0d4067/vim/vimrc#L878-L879), but it didn't work.

**Comment by wookayin** [comment]
Those L878-879 are the relevant lines.
```
autocmd FileType c,cpp,java,javascript,html,ruby,python,pandoc
      \ autocmd BufWritePre <buffer> :call StripTrailingWhitespaces()
```

I don't think there is any else configuration, so it should work. Have you tried restarting vim or reloading the buffer?

**Comment by wookayin** [comment]
I am closing this for now. Please let me know if you have any further questions.
