### ISSUE TITLE
How can I uninstall this?

### ISSUE THREAD

**Issue by JH713** [wookayin/dotfiles#35]
I install this by 'curl -fsSL https://dotfiles.wook.kr/etc/install | bash'.
And I want to uninstall this but i don't know how. 
Can you tell me how to uninstall this? 
Thank you.

**Comment by wookayin** [comment]
Hi, you can do the following:

```
rm -rf ~/.dotfiles
```

You may have a lot of (broken) symbolic links on your HOME folder, which should be taken care of manually. The list of all symlinks that would have been generated can be found in [install.py](https://github.com/wookayin/dotfiles/blob/master/install.py#L32): to name a few, you may want to remove the symbolic links like (not an exhaustive list)

* ~/.vimrc
* ~/.vim
* ~/.bashrc
* ~/.zsh
* ~/.zshrc
* ~/.tmux
* ~/.tmux.conf
* etc.

**Comment by wookayin** [comment]
Please feel free to comment here or reach out to me if you have any further questions.
