### ISSUE TITLE
Simple question: do you use VimR?

### ISSUE THREAD

**Issue by dukeow94** [wookayin/dotfiles#38]
I found the VimR configurations in `init.lua`. 
https://github.com/wookayin/dotfiles/blob/08ba0528f5f5a86da665639eec66b7e277594f9d/nvim/init.lua#L17-L22

Do you prefer using GUIs like VimR over using vim inside of a terminal?
And if you do, what makes you use VimR? (markdown preview maybe? 🤔 )

**Comment by wookayin** [comment]
Hi @dukeow94, thanks for your question. Most of the time I use vim inside a terminal, but sometimes I do use VimR as well. As a standalone macOS GUI app, it integrates well with macOS: for example, I can drag-and-drop a file from Finder into VimR to quickly open files (it's a bit complicated to do so with terminal). Markdown preview is also useful when editing README.md files :)

Please feel free to drop any further questions or suggestions if you have any.
