### ISSUE TITLE
zsh slows down when attemps to network drive

### ISSUE THREAD

**Issue by Corea** [wookayin/dotfiles#4]

**Comment by wookayin** [comment]
I believe this is mainly because the shell is trying to access to the disk to retrieve git status, or some other information...

**Comment by Corea** [comment]
Is there any option to turn off such things on specific directory?

**Comment by wookayin** [comment]
`command git config --bool prompt.showinfo` is being used in: https://github.com/sorin-ionescu/prezto/blob/master/modules/git/functions/git-info#L196-L198.

You can turn it off using `git-info false`, which basically does
```
git config prompt.showinfo false
```
inside a git working copy to disable scanning inside the directory.
