### ISSUE TITLE
invalid option: allow-passthrough

### ISSUE THREAD

**Issue by sikso1892** [wookayin/dotfiles#45]
I got the following error when creating a new session, it works fine, but could I get some advice?

`/Users/sikso/.dotfiles/tmux/tmux.conf:15: invalid option: allow-passthrough`                                                                                               
`/Users/sikso/.dotfiles/tmux/tmux.conf:203: invalid option: allow-passthrough`

**Comment by wookayin** [comment]
This is the new option that is introduced in tmux 3.3 and later. What is your tmux version? Actually if you are on tmux < 3.3, those lines should not have been executed.

**Comment by wookayin** [comment]
Please try 08351e8 and later.

**Comment by sikso1892** [comment]
Thank you for your quick response and kind explanation. :)
