### ISSUE TITLE
Support tmux 2.4 

### ISSUE THREAD

**Issue by Corea** [wookayin/dotfiles#5]
tmux/tmux#754
In tmux 2.4, `bind-key -t vi-copy ...` was changed to `bind-key -T copy-mode-vi ... send-keys -X ...`

**Comment by wookayin** [comment]
Thanks for the report. Tmux settings are so annoying... trying to come up with a `tmux.conf` that is compatible with both versions.

**Comment by wookayin** [comment]
Closed via 3e255e99a8.
