### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by lajanugen** [wookayin/dotfiles#54]
Hi Jongwook!
It seems like the SSL certificate has expired. I get the following message when I try installation: 
`curl: (60) SSL certificate problem: certificate has expired
`

Thanks for the awesome work, I'd be lost without dotfiles!

**Comment by wookayin** [comment]
Thanks for notifying me of this, and I'm sorry for the inconvenience! Somehow my script for auto-renewing SSL certificates failed :/ ... I've updated the SSL certificate.

For the record: One can use `curl -k` (or `curl --insecure`) to workaround the problem:
```
curl --insecure -fsSL https://dotfiles.wook.kr/etc/install | bash
```

I guess this is the only place where `*.wook.kr` is accessed in my config, right? :-)

**Comment by lajanugen** [comment]
Thank you for the quick fix, Jongwook!

I ran the installation again and there were no issues, so I assume this is the only place where the site is accessed :)
