### ISSUE TITLE
How to Remove the Red Column Line in Python Files

### ISSUE THREAD

**Issue by imj2185** [wookayin/dotfiles#60]
Thank you for sharing your dotfiles! They’ve been really helpful for learning and setting up Neovim.
I’m a beginner with Neovim, and I’ve noticed that a red column line appears specifically when I’m editing Python files. I’d like to remove it, but I’m unsure how to do so. Could you please let me know how I can adjust this?

**Comment by wookayin** [comment]
It is called the ["color column"](https://neovim.io/doc/user/options.html#'colorcolumn').

`:setlocal colorcolumn=` or `vim.opt_local.colorcolumn = ''` (in Lua).

See [`nvim/after/ftplugin/python.lua`](https://github.com/wookayin/dotfiles/blob/master/nvim/after/ftplugin/python.lua#16)
