### ISSUE TITLE
tmux installation script

### ISSUE THREAD

**Issue by hiwonjoon** [wookayin/dotfiles#7]
Doesn't it require `sudo` in front of `apt-get install` on the tmux installation script?

ubuntu-setup.sh#L78: [`apt-get install -y libevent-dev libncurses5-dev libutempter-dev || exit 1;`](https://github.com/wookayin/dotfiles/blob/master/etc/ubuntu-setup.sh#L78)

Also, for `make install`?

**Comment by wookayin** [comment]
You are correct -- both lines would require sudo.
